CREATE DATABASE Courses
GO

USE Courses
GO

CREATE TABLE COURSES(
	COURSE_ID int IDENTITY(1,1) NOT NULL,
	NAME nvarchar(50) NOT NULL,
	DESCRIPTION nvarchar(500) NOT NULL)
GO

CREATE TABLE GROUPS(
	GROUP_ID int IDENTITY(1,1) NOT NULL,
	COURSE_ID int NOT NULL,
	NAME nvarchar(50) NOT NULL)
GO

CREATE TABLE STUDENTS(
	STUDENT_ID int IDENTITY(1,1) NOT NULL,
	GROUP_ID int NOT NULL,
	FIRST_NAME nvarchar(50) NOT NULL,
	LAST_NAME nvarchar(50) NOT NULL)
GO
