USE Courses
GO

SELECT COURSES.NAME AS 'Course', CONCAT(STUDENTS.FIRST_NAME, ' ', STUDENTS.LAST_NAME) AS 'Student'
	FROM COURSES
	INNER JOIN GROUPS ON GROUPS.COURSE_ID = COURSES.COURSE_ID
	INNER JOIN STUDENTS ON GROUPS.GROUP_ID = STUDENTS.GROUP_ID
	ORDER BY COURSES.COURSE_ID, 'Student'
GO
